/* This file was generated by ODB, object-relational mapping (ORM)
 * compiler for C++.
 */

DROP TABLE IF EXISTS `people`;

CREATE TABLE `people` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `age` SMALLINT UNSIGNED NOT NULL)

CREATE TABLE `tools` (
  `id` BIGINT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
  `name` TEXT NOT NULL,
  `person_id` REFERENCE

transacetion()
person
// persos->tools()->first()
person->name("aaa");
persos->tools->first()->name("falj")
db->persist(person);
t.commt();



